### ISSUE TITLE
可以考虑增加一个参数配置 文件小于多少大小的不进行硬链接吗？

### ISSUE THREAD

**Issue by Oscar1011** [likun7981/hlink#1]
单位可以是KB 或者MB ，因为有的种子可能自带nfo和cover。 这些文件如果链接了可能会被刮削时覆盖掉。 也避免了手动删除这些文件的步骤。
感谢大佬

**Comment by wgq1991242** [comment]
现在有文件类型筛选，指定只链.mkv.mp4.ISO这些媒体文件就好了。

**Comment by likun7981** [comment]
目前有文件过滤功能
