### ISSUE TITLE
群晖运行出错

### ISSUE THREAD

**Issue by qlwz** [likun7981/hlink#106]
hlink --help
file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/paths.js:10
if (!(await checkPathExist(hlinkHomeDir))) {
      ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)

**Comment by likun7981** [comment]
node 版本过低，升级node版本尝试

**Comment by AlexANSO** [comment]
兄弟 要不然你就要升级node要不然就安装低版本的hlink
npm i -g hlink@1.0.3

**Comment by qlwz** [comment]
使用低版本已经解决
