### ISSUE TITLE
多文件目录下的文件单独建立以文件命名的文件夹

### ISSUE THREAD

**Issue by wxg1015** [likun7981/hlink#110]
是否可以增加一个给多目录下文件建立独立文件夹的功能   比如  目前硬连接过来的是  /硬连接目录/子目录/（1.mkv,2.mkv,3.mkv,4.5.6.7.8.......）
是否可以 增加一个开关实现
/硬连接目录/子目录/（1/1.mkv,2/2.mkv,3/.mkv,4.5.6.7.8.......）
目前的话似乎只有/硬连接目录下的单文件可以建立独立文件夹  
/硬连接目录/1.mkv==/硬连接目录/1/1.mkv

**Comment by likun7981** [comment]
没太明白这个功能的需求，目前只会给`硬链目录/1.mkv` 建立独立的文件夹。

**Comment by likun7981** [comment]
没有收到后续回复，我先关闭此issue，如果有需要你可以重新打开
