### ISSUE TITLE
docker更新到v.2.0.7后出现Error: ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by 781747217** [likun7981/hlink#113]
问题如题，没有找到原因，磁盘空间是足够的，发现无法通过GUI控制

**Comment by likun7981** [comment]
重启docker，试试 2.0.7 源代码没有任何变更，只是docker 支持配置 PUID, PGID, Umask了

**Comment by DDS-ALL** [comment]
有可能是权限问题，设置`PUID=0 PGID=0 UMASK=022`试试看
