### ISSUE TITLE
求助win10下的docker使用hlink一直提示无有效绝对路径

### ISSUE THREAD

**Issue by bbilyvm** [likun7981/hlink#115]
<a href="https://freeimage.host/i/H7m2o92"><img src="https://iili.io/H7m2o92.md.jpg" alt="H7m2o92.md.jpg" border="0"></a><br /><a target='_blank' href='https://freeimage.host/'></a><br />

如图只填了host为9090，下面的host path和container path不知道怎么填没填，pathsMapping: {}，试了'D:/qq': 'D:/qqylj'，'"D:/qq"': '"D:/qqylj"'，"D:/qq": "D:/qqylj"

**Comment by DDSDerek** [comment]
> [![H7m2o92.md.jpg](https://camo.githubusercontent.com/206e58127f1f74931ec7ee5ced091f03846815d294d5fcc32c5f34a5f8f5e5cd/68747470733a2f2f69696c692e696f2f48376d326f39322e6d642e6a7067)](https://freeimage.host/i/H7m2o92)
> 
> 如图只填了host为9090，下面的host path和container path不知道怎么填没填，pathsMapping: {}，试了'D:/qq': 'D:/qqylj'，'"D:/qq"': '"D:/qqylj"'，"D:/qq": "D:/qqylj"


`container path` 理解为容器内路径，按照linux格式填写，例`/data/data`

`host path` 理解为主机路径，按照Windows格式填写，例`C:\data\hlink`

**Comment by DDSDerek** [comment]
剩下的hlink的设置，也都要按照linux格式填写

**Comment by DDSDerek** [comment]
但是我要提醒的是，linux硬链接在Windows上是不支持的

**Comment by bbilyvm** [comment]
> 但是我要提醒的是，linux硬链接在Windows上是不支持的
> 
> 所以理论上设置完成也不能正常使用

多谢回复，目前已经找到了一个替代，方便win系统想用硬链接的，地址在，gitee搜索hlink
