### ISSUE TITLE
关于在关闭同步缓存的情况下查看同步日志？

### ISSUE THREAD

**Issue by 188334911** [likun7981/hlink#116]
关闭缓存后，此次硬链接只返回硬链接的条数，而没有具体同步哪些文件的连接，建议增加一个同步日志

**Comment by likun7981** [comment]
成功的没必要提示，失败的会提示。成功的你就在目标文件夹能看到了

**Comment by 188334911** [comment]
> 成功的没必要提示，失败的会提示。成功的你就在目标文件夹能看到了

文件太多的情况下很难查找，硬链接又不能根据文件时间来排序
