### ISSUE TITLE
有没有兴趣增加过滤文件夹名的功能

### ISSUE THREAD

**Issue by hlhk2017** [likun7981/hlink#12]
二刺螈用户表示收的番剧文件夹里会有CDs，SPs这类二级文件夹，并不想把它们也进行硬链接，试过改目录层级，但又会影响这种
> XXX剧集（一级目录）
  >s1（二级目录）
     >xxx.mkv(三级目录)
  >s2（二级目录）
   >xxx.mkv(三级目录)

结构的文件夹进行链接。

**Comment by likun7981** [comment]
考虑，后续支持

**Comment by likun7981** [comment]
已开始进入规划实现阶段

**Comment by likun7981** [comment]
https://hlink.likun.me/other/v2.html
