### ISSUE TITLE
请教一下关于复制脚本到TR中用于下载完成时触发的问题

### ISSUE THREAD

**Issue by leonchanithotmail** [likun7981/hlink#121]
请教一下，复制了脚本后，粘贴到TR设置中的“种子下载完成后执行以下脚本：”栏目中保存就可以了吗？我试了下载一个文件到已经配置好的目录好像没有反应，不会链接到对应的目录去。是我的使用方法不对吗？求教
<a href="https://www.z4a.net/image/2Y2NEI"><img src="https://www.z4a.net/images/2023/01/17/_20230117001440.md.png" alt="_20230117001440.png" border="0" /></a>

**Comment by likun7981** [comment]
看下tr的wiki里面说明
