### ISSUE TITLE
hlink 文件数与实际文件数不一致，并且硬链接之后，缺失一部分文件

### ISSUE THREAD

**Issue by LB-DotFish** [likun7981/hlink#124]
刚刚提了一个docker方式，hlink 2.0.8版本的问题（执行过程中，在文件名中插入特殊符号，以致文件不存在，进而程序崩溃）。

在2.0版本无法使用的情况下，采用hlink老版本，通过mjs 配置文件 和 命令行，进行硬链接。程序虽然能成功执行完成，但是查看对比发现，还是有些问题。

问题1：硬链接完成后，是缺少一些文件和目录的
问题2：hlink分析的文件数大于实际文件数

源文件夹
包含102582个文件，3028个目录

目标文件夹
包含102557个文件，3027个目录

可以看到硬链接完成后，是缺少一些文件和目录的。

还有就是hlink分析完毕，INFO 共计 120692 个文件。可以看到hlink分析的文件数大于实际文件数。

已经排查过，源文件夹不包含已排除文件，全部都是可以正常硬链接文件。

配置文件如下
// 重要说明路径地址都请填写 绝对路径！！！！
export default {
  /**
   * 源地址
   */
  source: "/volume1/second/pt/_downloads",
  /**
   * 目标地址
   */
  dest: "/volume1/second/pt/_hlink",
  /**
   * 需要包含的后缀名,如果不配置该项，会采用以下策略
   *  1. 配置了excludeExtname，则链接文件为排除后的其他文件
   *  2. 未配置excludeExtname，则链接文件为目录下的所有文件
   */
  includeExtname: [],
  /**
   * 需要排除的后缀名, 如果配置了includeExtname则该配置无效
   */
  excludeExtname: ["part", "!qB"],
  /**
   * 0：保持原有的目录结构
   * 1：只保存一级目录结构
   * 默认为 0
   * 例子：
   *  - 源地址目录为：/a
   *  - 目标地址目录为: /d
   *  - 链接的文件地址为 /a/b/c/z/y/mv.mkv；
   *  如果保存模式为0 生成的硬链地址为: /d/b/c/z/y/mv.mkv
   *  如果保存模式为1 生成的硬链地址为：/d/y/mv.mkv
   */
  saveMode: 0,
  /**
   * 是否打开缓存，默认关闭
   *
   * 打开后，每次硬链后会把对应文件存入缓存，就算下次删除硬链，也不会进行硬链
   */
  openCache: true,
  /**
   * 是否为独立文件创建同名文件夹，默认创建
   */
  mkdirIfSingle: false,
};

hlink执行记录如下：
任务计划程序已完成计划任务。

任务：hlink
开始时间：Sat, 28 Jan 2023 08:44:56 GMT
结束时间：Sat, 28 Jan 2023 09:09:45 GMT
当前状态：0 (正常)
标准输出/错误：
INFO 开始检查配置...
SUCCEED 配置检查完毕!现有配置为
INFO 源地址: /volume1/second/pt/_downloads
INFO 目标地址: /volume1/second/pt/_hlink
INFO 当前运行模式: 黑名单模式
INFO 使用的配置文件: /volume1/docker/hlink/config/hlink.config.mjs
INFO 排除的后缀有: part,!qb
INFO 硬链保存模式: 保持原有目录结构
INFO 是否开启缓存: 是

INFO 开始分析源目录..
SUCCEED 分析完毕!
INFO 共计 120692 个文件
INFO 不满足配置的文件 0 个
INFO 已存在硬链的文件 0 个
INFO 缓存的创建记录 0 条
INFO 需要硬链的文件 120692 个
INFO 开始执行...
INFO 如果你看到这个消息，说明你的bash不支持格式化输入
INFO 执行中，当前进度1/120692
INFO 执行中，当前进度2/120692

**Comment by likun7981** [comment]
建议排查下是否有隐藏文件
