### ISSUE TITLE
正向同步计划任务不生效

### ISSUE THREAD

**Issue by wxg1015** [likun7981/hlink#127]
docker部署的   硬链接和同步用的是同一个配置文件 这应该是没问题的吧 
然后 硬链接似乎没出现不自动执行的问题  
但是不知道为啥 正向同步就是不自动执行确认删除 看日志 任务本身是执行了  但是到最后确认删除环节 没有删除
 我添加了计划任务/循环执行都不行 
 手动点击任务就能正常执行 并要求我确认是否删除

**Comment by wxg1015** [comment]
![Uploading 屏幕截图 2023-02-03 210919.png…]()

**Comment by wxg1015** [comment]
> 你计划任务，用的什么添加的？

同步的话 循环和定时都有尝试 不行
  硬链接的话只用过 循环 没问题

**Comment by wxg1015** [comment]
> 你计划任务，用的什么添加的？

我再试试定时  给您个确定的反馈

**Comment by wxg1015** [comment]
> 你计划任务，用的什么添加的？

![IMG_20230210_164818_604.jpg](https://user-images.githubusercontent.com/44153358/218045918-b100d5ce-c0e3-437f-93d5-a7854c9a6e76.jpg)

![IMG_20230210_164824_272.jpg](https://user-images.githubusercontent.com/44153358/218045965-7c096fc7-b146-4482-8f11-d38f924c1577.jpg)

![IMG_20230210_164821_713.jpg](https://user-images.githubusercontent.com/44153358/218045989-11139d65-5200-4800-866a-12b8ba302e60.jpg)

不行  计划任务也不行

**Comment by likun7981** [comment]
这应该是一个bug，那个二次确认项理论上在 计划任务不应该提示

**Comment by likun7981** [comment]
已经发布v2.0.9
