### ISSUE TITLE
可不可以不管后缀名，所有内容都链接上？

### ISSUE THREAD

**Issue by cnh3303** [likun7981/hlink#13]
原盘（非ISO）文件，硬链接后用蓝光机播放不了，没链接的可以播，对发现是硬链接的文件不全（没在后缀名列表里）

**Comment by likun7981** [comment]
黑名单模式开发中，关注https://github.com/likun7981/hlink/pull/11

**Comment by likun7981** [comment]
已发布beta版本 使用 npm i -g hlink@beta 体验，有问题及时反馈
