### ISSUE TITLE
提示你的bash不支持格式化输入并且扫描不到文件

### ISSUE THREAD

**Issue by jialifushi** [likun7981/hlink#133]
在解决完报错：源目录不存在后，能扫描了，但是扫描到一个文件，并且还提示可能你的bash不支持。[](url)
<img width="1044" alt="iShot2023-03-11 14 46 58" src="https://user-images.githubusercontent.com/101686929/224469817-b220bb46-d54a-4464-a94f-25ba32956984.png">
<img width="1040" alt="iShot2023-03-11 14 47 16" src="https://user-images.githubusercontent.com/101686929/224469818-eb4f89d4-1854-49f6-942c-4b07294a6e3b.png">
<img width="1057" alt="iShot2023-03-11 14 49 39" src="https://user-images.githubusercontent.com/101686929/224469835-95e81aca-e507-424c-9912-ea3ada1d9aa4.png">

**Comment by likun7981** [comment]
cross-device link，就是跨共享文件夹 或者 跨盘

**Comment by likun7981** [comment]
> 我并没有跨盘，难道是因为组了raid1的原因吗？这个会报这个错？

你可以尝试使用系统最底层的`ln` 命令，如果这个命令报错，说明肯定是有跨盘 或者 跨共享文件夹的，是系统限制，hlink无法解决的
