### ISSUE TITLE
生成的硬链接文件及文件夹无法编辑提示权限问题

### ISSUE THREAD

**Issue by bearcloney** [likun7981/hlink#134]
https://i.328888.xyz/2023/03/26/iDGVY8.png
https://i.328888.xyz/2023/03/26/iDdbH5.png
运行nas unraid系统，docker

**Comment by ReddotCleaner** [comment]
尝试添加两个环境变量，如下图，就是你smb用户的GUID和PUID
![image](https://user-images.githubusercontent.com/34325738/228138344-f2fef649-a100-400e-82cc-4248743129f3.png)

**Comment by SuLiu99** [comment]
> 尝试添加两个环境变量，如下图，就是你smb用户的GUID和PUID ![image](https://user-images.githubusercontent.com/34325738/228138344-f2fef649-a100-400e-82cc-4248743129f3.png)

这样做会导致执行报错 权限不够，但是我是给了这个用户读写权限的

**Comment by SuLiu99** [comment]
> https://i.328888.xyz/2023/03/26/iDGVY8.png https://i.328888.xyz/2023/03/26/iDdbH5.png 运行nas unraid系统，docker

我也遇到了同样的问题 在WINDOWS下的共享文件夹里 无权修改硬链的文件 但是同样在docker运行的filebrower就可以修改。这样我没法在Windows下使用批量重命名工具

**Comment by ReddotCleaner** [comment]
> > https://i.328888.xyz/2023/03/26/iDGVY8.png https://i.328888.xyz/2023/03/26/iDdbH5.png 运行nas unraid系统，docker
> 
> 我也遇到了同样的问题 在WINDOWS下的共享文件夹里 无权修改硬链的文件 但是同样在docker运行的filebrower就可以修改。这样我没法在Windows下使用批量重命名工具

之前的hlink确实会有这样的问题，但是这个问题已经在最近的几个版本更新修复了；hlink版本2.0.9，unraid版本6.11.5，设置好权限掩码之后，文件硬链后可以正常移动、改名。如果你用的是2.0.7之前的版本，请尝试更新至最新版
