### ISSUE TITLE
unraid环境下docker版报跨盘错误，但ln命令能成功

### ISSUE THREAD

**Issue by 77-arthur** [likun7981/hlink#135]
情况说明
在UI界面里运行运行任务报跨盘错误，能在正确对应目录下创建同名文件夹，不过不能创建硬链接。
经过测试，可以通过`ln`命令手动建立文件硬链接，并进行刮削和播放。

映射路径
/download：.../user/download/medias
/medias: .../user/medias/media
配置路径
'/download/anime': '/medias/anime'

错误log
```
Error: Command failed with exit code 1: ln /download/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语].mp4 /medias/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语]
ln: /medias/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语]/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语].mp4: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /download/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语].mp4 /medias/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语]
ln: /medias/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语]/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语].mp4: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /download/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语].mp4 /medias/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语]',
  command: 'ln /download/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语].mp4 /medias/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语]',
  escapedCommand: 'ln "/download/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语].mp4" "/medias/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语]"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /medias/anime/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语]/[V2][织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][08集][1080P][AVC][简日双语].mp4: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.14.1
````

bash ln命令

![image](https://user-images.githubusercontent.com/50293747/228804865-b8809bab-0e06-4cf1-9bd5-c99700c66b46.png)

docker配置
![image](https://user-images.githubusercontent.com/50293747/228806457-db4660f4-ead5-452b-ba42-0c8b84d71ed3.png)

**Comment by 77-arthur** [comment]
通过阅读hlink的[docker安装指南](https://hlink.likun.me/other/v2.html#_1%E3%80%81%E4%BD%BF%E7%94%A8-docker-%E6%8E%A8%E8%8D%90)中对映射路径的解释，已经解决此问题。

不过产生一个新问题，win上通过smb访问会因为权限不足无法修改，导致无法刮削。
目前解决方案是使用[docker版的tmm](https://hub.docker.com/r/dzhuang/tinymediamanager)来进行刮削

**Comment by likun7981** [comment]
> 通过阅读hlink的[docker安装指南](https://hlink.likun.me/other/v2.html#_1%E3%80%81%E4%BD%BF%E7%94%A8-docker-%E6%8E%A8%E8%8D%90)中对映射路径的解释，已经解决此问题。
> 
> 不过产生一个新问题，win上通过smb访问会因为权限不足无法修改，导致无法刮削。 目前解决方案是使用[docker版的tmm](https://hub.docker.com/r/dzhuang/tinymediamanager)来进行刮削

可以在安装时，指定下PUID, PGID来做权限控制，参考下这个https://github.com/likun7981/hlink/pull/112

**Comment by 77-arthur** [comment]
> > 通过阅读hlink的[docker安装指南](https://hlink.likun.me/other/v2.html#_1%E3%80%81%E4%BD%BF%E7%94%A8-docker-%E6%8E%A8%E8%8D%90)中对映射路径的解释，已经解决此问题。
> > 不过产生一个新问题，win上通过smb访问会因为权限不足无法修改，导致无法刮削。 目前解决方案是使用[docker版的tmm](https://hub.docker.com/r/dzhuang/tinymediamanager)来进行刮削
> 
> 可以在安装时，指定下PUID, PGID来做权限控制，参考下这个#112

好的谢谢！添加对应的UID和GID后能使用smb远程刮削

**Comment by latel** [comment]
> 通过阅读hlink的[docker安装指南](https://hlink.likun.me/other/v2.html#_1%E3%80%81%E4%BD%BF%E7%94%A8-docker-%E6%8E%A8%E8%8D%90)中对映射路径的解释，已经解决此问题。
> 
> 不过产生一个新问题，win上通过smb访问会因为权限不足无法修改，导致无法刮削。 目前解决方案是使用[docker版的tmm](https://hub.docker.com/r/dzhuang/tinymediamanager)来进行刮削

咋解决的老哥，我看你上面的贴图好像没啥问题啊
