### ISSUE TITLE
WEBUI界面建议增加版本提示

### ISSUE THREAD

**Issue by Juway111** [likun7981/hlink#137]
好久没有更新了，找不到自己当前哪个版本

**Comment by likun7981** [comment]
当前有需要更新的版本，就会有提示。如果没有提示，就说明是最新版本

**Comment by likun7981** [comment]
https://github.com/likun7981/hlink/releases/tag/app%402.0.0-next.28

**Comment by Juway111** [comment]
好的，明白了
