### ISSUE TITLE
大佬，一直无法成功使用是什么原因

### ISSUE THREAD

**Issue by emoday** [likun7981/hlink#14]
全是错误代码：[HLINK ERROR]: Error: Command failed with exit code 1 (EPERM)

群晖918+ SSH里使用HLINK的命令，文件夹都能过去 文件一个过不去~~

**Comment by likun7981** [comment]
跨盘的原因，硬链不能跨盘

**Comment by emoday** [comment]
老哥 没跨盘啊。。。同盘建立的。。同一个空间。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "likun7981/hlink"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 上午10:02
收件人:&nbsp;"likun7981/hlink"<hlink@noreply.github.com&gt;;
抄送:&nbsp;"12640605"<12640605@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [likun7981/hlink] 大佬，一直无法成功使用是什么原因 (#14)





 
跨盘的原因，硬链不能跨盘

**Comment by likun7981** [comment]
不一定是物理跨盘，有可能是逻辑盘，你用cp -lr 试试就知道了？
