### ISSUE TITLE
使用npm安装hlink后如何卸载呢？

### ISSUE THREAD

**Issue by 1tonsilla** [likun7981/hlink#142]
我用synology，我用npm安装hlink后，后悔了，于是换成docker安装。

然后搜了下npm卸载，用了npm uninstall -g hlink卸载，但是发现好像卸载不干净？（如图，packages 388全部卸载了，但是audited安装时候是389，卸载时候变成1个了呢？）

咋样能卸载干净点呢？
![image](https://pic7.58cdn.com.cn/nowater/webim/big/n_v2e7b91ce5c39e436c9822d9e4da44c6e5.png)

**Comment by likun7981** [comment]
uninstall 就能卸载干净。
