### ISSUE TITLE
报错 运行的时候，第一次没有错误，第二次错误了

### ISSUE THREAD

**Issue by wangwei2022nov** [likun7981/hlink#145]
file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:38
        waitLinkFiles.push(...item.waitLinkFiles);
                      ^

RangeError: Maximum call stack size exceeded
    at file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:38:23
    at Array.forEach ()
    at hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:37:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)

Node.js v18.14.1

**Comment by wangwei2022nov** [comment]
export default {
  /**
   * 源路径与目标路径的映射关系
   * 例子:
   *  pathsMapping: {
   *     '/path/to/exampleSource': '/path/to/exampleDest',
   *     '/path/to/exampleSource2': '/path/to/exampleDest2'
   *  }
   */
  pathsMapping: {
        '/downloads/media/audiobooks': '/downloads/media/Alink/audiobooks'
      
        
  },
  /**
   * 需要包含的后缀，如果与exclude同时配置，则取两者的交集
   * include 留空表示包含所有文件
   *
   * 后缀不够用? 高阶用法: todo 待补充链接
   */
  include: [],
  /**
   * 需要排除的后缀，如果与include同时配置，则取两者的交集
   *
   * 后缀不够用? 高阶用法: todo 待补充链接
   */
  /**exclude: ['jpg','jpeg','png','nfo','txt','md5'],*/
  /**
   * @scope 该配置项 hlink 专用
   * 是否保持原有目录结构，为false时则只保存一级目录结构
   * 可选值: true/false
   * 例子：
   *  - 源地址目录为：/a
   *  - 目标地址目录为: /d
   *  - 链接的文件地址为 /a/b/c/z/y/mv.mkv；
   *  如果设置为true  生成的硬链地址为: /d/b/c/z/y/mv.mkv
   *  如果设置为false 生成的硬链地址为：/d/y/mv.mkv
   */
  keepDirStruct: true,
  /**
   * @scope 该配置项 hlink 专用
   * 是否打开缓存，为true表示打开
   * 可选值: true/false
   * 打开后，每次硬链后会把对应文件存入缓存，就算下次删除硬链，也不会进行硬链
   */
  openCache: true,
  /**
   * @scope 该配置项 hlink 专用
   * 是否为独立文件创建同名文件夹，为true表示创建
   * 可选值: true/false
   */
  mkdirIfSingle: true,
  /**
   * @scope 该配置项为 hlink prune 命令专用
   * 是否删除文件及所在目录，为false只会删除文件
   * 可选值: true/false
   */
  deleteDir: true,
}
配置文件是这个。

**Comment by wangwei2022nov** [comment]
RangeError: Maximum call stack size exceeded  docker 启动 是这个

**Comment by likun7981** [comment]
文件太多了，先放到 #141 追踪，这个先关了
