### ISSUE TITLE
Docker中创建的Hlink，请问配置文件会保存到宿主机吗

### ISSUE THREAD

**Issue by Dunky-Z** [likun7981/hlink#147]
之前创建了很多配置，也建立了很多缓存，今天Recreate容器了，发现配置都没了。按理来说配置文件不都映射到宿主机config目录里吗。没有找到配置文件，也没有找到缓存文件。请问配置文件保存位置在哪呢？谢谢

**Comment by likun7981** [comment]
存放的路径是 这个环境变量`HLINK_HOME ` ，要看你指定的地址有没映射到宿主机
