### ISSUE TITLE
prune 时删除刮削资源（海报、nfo、字幕等）

### ISSUE THREAD

**Issue by zhaoyibo** [likun7981/hlink#157]
在硬链接的目录直接刮削资源，会有些海报图片、nfo、字幕等文件。
在使用 prune 同步目录进行清理的时候，用的 docker 版 webui，已经配置了 `deleteDir: true`。
硬链接的文件确实被删除了， 但是这些刮削资源还在目录里，目录也就无法被删除。

希望能增加选项，在 prune 的时候，可以同步删除目录中这种非硬链接资源，进而能把文件夹给删掉。

**Comment by likun7981** [comment]
`deleteDir`的设计就是这个为了这个事情，会删除文件所在目录，你现在的场景 是不是 文件所在二层目录还存在关联文件？

**Comment by zhaoyibo** [comment]
我今天删的电影，看是删干净了。
之前删的是剧集，是还留着目录和刮削资源。`deleteDir=true`时，剧集是会先删每个 E 文件夹，再最后删 S 文件吗？

**Comment by likun7981** [comment]
> 我今天删的电影，看是删干净了。 之前删的是剧集，是还留着目录和刮削资源。`deleteDir=true`时，剧集是会先删每个 E 文件夹，再最后删 S 文件吗？

剧集应该是因为有两层目录导致的吧，
举例子：

`/xxx/dir/movie1.mkv` 

- 如果配置 `deleteDir=true` 则会直接删除`movie1.mkv`所在的`dir`目录及其下面所有文件
- 如果配置 `deleteDir=false` 则只会删除`movie1.mkv`文件本身

**Comment by zhaoyibo** [comment]
嗯，那就清楚了。
是因为剧集套了两层目录的原因。
