### ISSUE TITLE
是否可以增加成图形界面

### ISSUE THREAD

**Issue by xmxu2022** [likun7981/hlink#158]
目前硬链在是用代码编辑配置，是否可以新增图形化的界面，直接选择源文件地址，完事选择目前文件夹，点个开始就可以直接硬链完成，类似于nastools那种形式，会更直观一些。

**Comment by likun7981** [comment]
> 目前硬链在是用代码编辑配置，是否可以新增图形化的界面，直接选择源文件地址，完事选择目前文件夹，点个开始就可以直接硬链完成，类似于nastools那种形式，会更直观一些。

短时间内可能不会支持，因为目前配置不复杂。
