### ISSUE TITLE
请问我是在Mac上使用docker desktop安装，我该怎么设置文件路径

### ISSUE THREAD

**Issue by keeper-0** [likun7981/hlink#159]
我目前是使用的“/Users/wuti/文档/Box/TV”，执行时，显示源路径不存在。请问我应该怎么配置路径呢
![Uploading 截屏2023-11-21 00.12.22.png…]()
![Uploading 截屏2023-11-21 00.12.08.png…]()

**Comment by keeper-0** [comment]
<img width="481" alt="截屏2023-11-21 00 12 22" src="https://github.com/likun7981/hlink/assets/93301915/a1e981f6-1f40-4bd5-8107-0552ec738f19">
<img width="793" alt="截屏2023-11-21 00 12 08" src="https://github.com/likun7981/hlink/assets/93301915/dd6aab92-8f76-49f9-9fb0-79c3a74b71d3">

**Comment by komaedaXnagito** [comment]
请问一下怎么解决的？我群晖也遇到同样的问题

**Comment by ghost** [comment]
> 请问一下怎么解决的？我群晖也遇到同样的问题

指定路径为docker映射的，而不是实际的文件路径
