### ISSUE TITLE
偶然发现webui没有屏蔽公网访问

### ISSUE THREAD

**Issue by NieRNEST** [likun7981/hlink#160]
偶然发现webui没有屏蔽公网访问，使用ipv6加端口可以直连，有一定安全风险，希望加入密码或者类似ddnsgo的禁止公网访问功能

**Comment by calvinchai** [comment]
我觉得首先你得自己开个防火墙。不少人这类服务都是只跑内网或者反代了的

**Comment by NieRNEST** [comment]
> 我觉得首先你得自己开个防火墙。不少人这类服务都是只跑内网或者反代了的

唉，硬路由防火墙一根筋，v4关不掉，v6开不了，导致安全防护全靠webui加密，常用服务反代也配置了，只是ip直连就没办法了，突然想到nas应该可以屏蔽特定端口，有救了

**Comment by calvinchai** [comment]
> > 我觉得首先你得自己开个防火墙。不少人这类服务都是只跑内网或者反代了的
> 
> 唉，硬路由防火墙一根筋，v4关不掉，v6开不了，导致安全防护全靠webui加密，常用服务反代也配置了，只是ip直连就没办法了，突然想到nas应该可以屏蔽特定端口，有救了

你nas可以自己配置iptable的
