### ISSUE TITLE
威联通部署后提示 Error:ENOSPC: no space left on device, wirte

### ISSUE THREAD

**Issue by robinletian** [likun7981/hlink#161]
按照
version: '3'

services:
  docker:
    image: likun7981/hlink:latest # docker镜像名称
    restart: on-failure
    ports: # 这个端口映射
      - 9090:9090
    volumes: # 这个表示存储空间映射
      - /share:/share
    environment:
      - HLINK_HOME=/share/data/hlinkDocker # 这个是环境变量

这个直接安装的，一直重启。Container Station 3.0.5

![ZO_IJ`IV`E U9RFMSMXR692](https://github.com/likun7981/hlink/assets/58308487/bf901e70-942d-4c5e-9f56-c89119fb0afd)

**Comment by robinletian** [comment]
下载容器手动设置储存后ok了。做了个软连接,从/share/Container/hlink到/share
![PE@ 9H%7O2LRZ$4CVHW_@UT](https://github.com/likun7981/hlink/assets/58308487/67edaa14-203c-4f7a-a6f4-675dfe17c36a)

**Comment by likun7981** [comment]
空间不足的原因
