### ISSUE TITLE
请问支持unraid的docker吗

### ISSUE THREAD

**Issue by latel** [likun7981/hlink#169]
unraid的文件系统好像是mergefs

**Comment by ReddotCleaner** [comment]
支持的

**Comment by latel** [comment]
@ReddotCleaner 可以这样配置吗
unraid服务器上 a, b两个目录，配置两个映射到容器内的/a, /b 两个目录，然后配置hlink硬链/a里的文件到/b吗？

**Comment by ReddotCleaner** [comment]
> @ReddotCleaner 可以这样配置吗 unraid服务器上 a, b两个目录，配置两个映射到容器内的/a, /b 两个目录，然后配置hlink硬链/a里的文件到/b吗？

![image](https://github.com/likun7981/hlink/assets/34325738/f7cf4dad-47d7-4415-b509-60735ec34bcd)
这是我的配置，建议映射a,b目录的上层目录X到hlink容器内，然后硬链，当然你也可以先试试你的方法，理论上没有问题

**Comment by latel** [comment]
@ReddotCleaner 多谢指教，如果我/a和/b分别挂载的话，HLINK_HOME目录可以和/a、/b都不一样，统一放unraid的标准目录 /mnt/user/appdata/hlink/吗？

我其实想创建2个单独的share， /downloads和/media，/media是刮削好的分享，/downloads只负责往里面塞下载的源文件默认不对外分享。

**Comment by latel** [comment]
其实我不太明白，感觉hlink应该要求源文件和创建的硬链应该都需要在同一个磁盘上？  问题是unraid同一个share里的文件，可能是分配在好几个物理硬盘上的

**Comment by latel** [comment]
我实验了这样不行
```
/mnt/user/a -> /a
/mnt/user/b -> /b
/mnt/user/appdata/hlink -> /config
# HLINK_HOME=/config
```

参考你的直接传上层可以
```
/mnt/user -> /data
# HLINK_HOME=/data/appdata/hlink
```

**Comment by ReddotCleaner** [comment]
> 其实我不太明白，感觉hlink应该要求源文件和创建的硬链应该都需要在同一个磁盘上？ 问题是unraid同一个share里的文件，可能是分配在好几个物理硬盘上的

你直接映射unraid的/mnt/user下面的目录进去就行，跨盘的事情unraid会自己解决

**Comment by latel** [comment]
嗯，可以了
