### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by dizicheng** [likun7981/hlink#17]
WIN10
node v12.16.1
![image](https://user-images.githubusercontent.com/21209008/114376620-5e1a4600-9bb8-11eb-9250-c48778c64b50.png)
![image](https://user-images.githubusercontent.com/21209008/114376477-3d51f080-9bb8-11eb-938d-97cbdb10eb09.png)

**Comment by likun7981** [comment]
Windows的 请使用 git bash ，其他终端没有适配

**Comment by likun7981** [comment]
https://github.com/likun7981/hlink/issues/10#issuecomment-751252158

**Comment by dizicheng** [comment]
嗯已解决，但是smb映射的盘还有问题
![image](https://user-images.githubusercontent.com/21209008/114530497-8e77e800-9c7d-11eb-8ef4-78beedccc80e.png)

**Comment by dizicheng** [comment]
已解决，感谢
