### ISSUE TITLE
关于GUI下使用prune命令

### ISSUE THREAD

**Issue by chinaqy110** [likun7981/hlink#172]
GUI下如何使用prune命令正向检查并删除多余硬链接呢，看配置文件没有这个内容，看了网站教程都是命令行，但是升级了GUI的版本后不支持命令行了~先谢谢大佬，工具超好用

**Comment by latel** [comment]
![image](https://github.com/likun7981/hlink/assets/5621862/cb28893a-002a-4117-bf01-2de88bc44b7e)

**Comment by chinaqy110** [comment]
原来这样，感谢大佬
