### ISSUE TITLE
希望增加复制.nfo这些文件的功能

### ISSUE THREAD

**Issue by meatballgithub** [likun7981/hlink#18]
硬链接.mkv这类文件彻底解决了刮削使得.nfo这类文件改变导致的红种问题。不过有些种子自带了刮削文件，建议增加一个复制（非硬链接）.nfo类文件到dst的功能。这样对于自带刮削文件的种子来说，操作之后在dst文件夹内既有.mkv文件，也有.nfo文件，可以使用自带的刮削信息，同时可以避免如果之后播放器重新刮削导致.nfo文件变化红种（因为是复制过来的，所以在dst内修改.nfo文件并不会影响源文件）

**Comment by imogel** [comment]
> 硬链接.mkv这类文件彻底解决了刮削使得.nfo这类文件改变导致的红种问题。不过有些种子自带了刮削文件，建议增加一个复制（非硬链接）.nfo类文件到dst的功能。这样对于自带刮削文件的种子来说，操作之后在dst文件夹内既有.mkv文件，也有.nfo文件，可以使用自带的刮削信息，同时可以避免如果之后播放器重新刮削导致.nfo文件变化红种（因为是复制过来的，所以在dst内修改.nfo文件并不会影响源文件）

软件自带白名单功能，建议使用此功能，在操作时添加"-i"参数指定文件类型。更多信息请参考“# hlink --help”
