### ISSUE TITLE
[Feature]希望增加自定义【配置文件】路径

### ISSUE THREAD

**Issue by kirincc** [likun7981/hlink#19]
由于威联通重启后，会重置某些系统配置，包括 /root 目录。hlink 目前创建的配置文件，是放在了 /root 目录下，威联通重启后，会被重置删掉。

所以希望增加自定义【配置文件】路径的配置项。

**Comment by likun7981** [comment]
`hlink -g 生成路劲`

`hlink -c 使用配置文件路劲`

当前已经支持
