### ISSUE TITLE
[Improvement]希望硬链结果能够更加详细

### ISSUE THREAD

**Issue by kirincc** [likun7981/hlink#20]
当前硬链结果只显示统计数据，没有具体成功与失败的文件列表，不方便找到原因。

因此希望结果能够更加详细，列出具体成功的文件，与失败的文件。

**Comment by likun7981** [comment]
后续考虑优化下 输出的日志，给用户配置输出内容

**Comment by likun7981** [comment]
已实现，安装最新版本
