### ISSUE TITLE
硬链接改名后无法识别，会重复添加

### ISSUE THREAD

**Issue by Viweday** [likun7981/hlink#22]
![image](https://user-images.githubusercontent.com/20718026/118144895-8effcc00-b43f-11eb-9e23-542f6c7f0ef8.png)

Readme里说创建硬链时，会自动检测硬链接是否存在，硬链改名后同样能检测到，但实际上，我对A创建了一个硬链B，然后把B改名为C，再运行一次创建硬链的脚本时，B又会被创建出来，于是我就有了A的硬链B、C

**Comment by likun7981** [comment]
已核实 路劲问题
