### ISSUE TITLE
现在有过滤文件夹的功能了嘛？

### ISSUE THREAD

**Issue by foreverlong** [likun7981/hlink#23]
大佬 现在有过滤文件夹的功能了嘛？ 因为有时候pt下载了多个版本的电影用来做种，而需要emby识别的只有其中的一个

**Comment by wgq1991242** [comment]
目前没有。有这个需求，只能通过源目录的分类来规划了。

**Comment by xxzj990** [comment]
我觉得是不是可以加入关键字黑名单功能？出现关键字的文件夹或者文件就不链接。
有一个类似的需求是有的电影下载后会有Sample文件夹，里面是是一个小的视频文件，这个一般都不需要，emby搜刮的时候会多一个。
仅仅是建议，大佬可以考虑考虑~目前对我来说，功能已经很不错了，感谢大佬的无私付出~~

**Comment by likun7981** [comment]
> 我觉得是不是可以加入关键字黑名单功能？出现关键字的文件夹或者文件就不链接。
> 有一个类似的需求是有的电影下载后会有Sample文件夹，里面是是一个小的视频文件，这个一般都不需要，emby搜刮的时候会多一个。
> 仅仅是建议，大佬可以考虑考虑~目前对我来说，功能已经很不错了，感谢大佬的无私付出~~

可以考虑

**Comment by habren** [comment]
> > 我觉得是不是可以加入关键字黑名单功能？出现关键字的文件夹或者文件就不链接。
> > 有一个类似的需求是有的电影下载后会有Sample文件夹，里面是是一个小的视频文件，这个一般都不需要，emby搜刮的时候会多一个。
> > 仅仅是建议，大佬可以考虑考虑~目前对我来说，功能已经很不错了，感谢大佬的无私付出~~
> 
> 可以考虑

你好，这个关键字黑名单或者文件夹黑名单功能预计什么时候上线呀？挺实用的功能

**Comment by likun7981** [comment]
关闭此issue 在https://github.com/likun7981/hlink/issues/12 进行追踪
