### ISSUE TITLE
hlink 未能正确判断源目录中的文件改动，对源目录新增的文件提示“硬链已存在, 跳过创建”

### ISSUE THREAD

**Issue by xdujiang** [likun7981/hlink#27]
source 目录 A 目录原本的文件结构如下：
```
A
|-B
  |-B1.mp4
```
首先对 A 执行了 hlink，正确在 target 目录下生成了目录 B 和其下文件 B1.mkv 的硬链接。
然后向 A 中添加了新目录 C 和文件 C1.mkv，A目录结构变为：
```
A
|-B
  |-B1.mp4
  |-C
    |-C1.mkv
```

重新运行 hlink，log 中提示  

> [HLINK WARN]: 源地址 A/B/C/C1.mkv 硬链已存在, 跳过创建

此时 target 目录下文件无变化，仍只有目录 B 和文件 B1.mkv。

请问这个问题可能出在哪呢？

另外，如果方便的话可以麻烦谈谈是如何做到“重复硬链检测”功能的么？我对 js 不大了解，没找到或者没看明白相应的代码段... 谢谢

hlink 版本为8月22日使用 npm 安装的版本，最大查找层级能够覆盖到相应文件。
hlink 配置如下：
```
[HLINK INFO]: 配置检查完毕...
[HLINK INFO]: 当前为 白名单 模式
[HLINK INFO]: 当前配置为:
[HLINK INFO]:   源地址: /volume2/TVshow/source
[HLINK INFO]:   目标地址: /volume2/TVshow
[HLINK INFO]:   包含的后缀有: mp4,flv,f4v,webm,m4v,mov,cpk,dirac,3gp,3g2,rm,rmvb,wmv,avi,asf,mpg,mpeg,mpe,vob,mkv,ram,qt,fli,flc,mod,iso
[HLINK INFO]:   最大查找层级为: 6
[HLINK INFO]:   硬链保存模式: 保持原有目录结构
```

**Comment by likun7981** [comment]
目标地址不要包含源地址，你这个配置 目标地址包含了源地址~，所以检测的时候 可能是检测到了源地址里面的文件

**Comment by likun7981** [comment]
> 如何做到“重复硬链检测”

看下这段[代码](https://github.com/likun7981/hlink/blob/45ff538efa11a2ad1025eb0d502ce08d4e0196db/src/utils/index.ts#L39-L56)

**Comment by xdujiang** [comment]
非常感谢，我重新试了一下，的确是因为目标地址包含源地址导致的这个问题。（果然是程序员永远也不知道用户会怎么使用程序）

学习了一下“重复硬链检测”的代码段，我的理解是先读取 source 中文件的 inode 号，然后查找 target 中是否存在同为该 inode 号的文件，若存在则说明已有硬链接。这样的话似乎可以通过在 find 命令中加入参数排除 source 目录来解决该问题？

在 source 和 target 都使用绝对路径的情况下，使用 “-prune” 参数可以排除 source 目录下的相应文件。
`find <target> -path <source> -prune -false -o -inum <inode_num>`

**Comment by xdujiang** [comment]
还有个问题，现在程序似乎无法手动停止执行？

在终端中按 ctrl-c，程序还是继续跑，需要断掉终端才能停下程序，请问这个是设计如此还是？
