### ISSUE TITLE
根目录下文件硬链接自动生成文件夹的功能可否做成可选功能

### ISSUE THREAD

**Issue by kangbeicai** [likun7981/hlink#28]
这个功能大部分情况下确实很方便，不过有时候多个文件还是想先硬链接完以后再手动放到一个文件夹下，这样增加了多余的无谓的工作量。 希望可以把这个功能做成可选的。

**Comment by xdujiang** [comment]
“saveLevel” 参数就是用来干这个事的啊...

**Comment by kangbeicai** [comment]
> “saveLevel” 参数就是用来干这个事的啊...

不一样啊， 默认的是保持原有目录结构，这种模式下，根目录的文件就变成生成同名文件夹下的文件，我所针对的就是这种情况。
保留一级目录，就是只有一级目录，原本二级目录下的文件夹都会变成一级目录。

**Comment by likun7981** [comment]
已添加 `mkdirIfSingle` 配置 详情见 https://github.com/likun7981/hlink/pull/32

抢先体验见： https://github.com/likun7981/hlink/releases/tag/v0.3.2-0
