### ISSUE TITLE
.!qB后缀文件黑名单无法过滤

### ISSUE THREAD

**Issue by kangbeicai** [likun7981/hlink#29]
因为个人习惯在qb下载的时候添加!qB后缀标识未完成的文件，并且不额外设置未完成的文件保存路径（避免文件下载完成后移动文件）。
为了避免自动硬链接的时候将未完成的文件也进行硬链接，想对!qB后缀进行黑名单过滤，但是发现实际未生效，测试其他常用后缀nfo,jpg等未出现该问题。

**Comment by xxzj990** [comment]
遇到了同样的问题，临时解决方法如下。
在硬链目录执行：
`find . -name '*.!qB' -exec rm -rf {} \;`

一定要在硬链后的目录执行，否则有可能把正在下载的文件删掉！

**Comment by kangbeicai** [comment]
> 遇到了同样的问题，临时解决方法如下。
> 在需要删除!qB文件的目录执行：
> `find . -name '*.!qB' -exec rm -rf {} \;`
> 
> 一定要在需要删除!qB文件的目录执行，否则有可能把正在下载的文件删掉！
这个太暴力了。。 我现在设置不添加!qb，习惯了也还挺好的。

**Comment by xxzj990** [comment]
> > 遇到了同样的问题，临时解决方法如下。
> > 在需要删除!qB文件的目录执行：
> > `find . -name '*.!qB' -exec rm -rf {} \;`
> > 一定要在需要删除!qB文件的目录执行，否则有可能把正在下载的文件删掉！
> 
> 这个太暴力了。。 我现在设置不添加!qb，习惯了也还挺好的。

不加!qB在unraid下容易出错，因为unraid文件是分布在不同盘的，如果恰好创建任务的时候所选的盘容量不够，就会导致下载后期出错。只有打开!qB，系统才会分配到容量足够的硬盘。

**Comment by xxzj990** [comment]
> > > > 遇到了同样的问题，临时解决方法如下。
> > > > 在需要删除!qB文件的目录执行：
> > > > `find . -name '*.!qB' -exec rm -rf {} \;`
> > > > 一定要在需要删除!qB文件的目录执行，否则有可能把正在下载的文件删掉！
> > > 
> > > 
> > > 这个太暴力了。。 我现在设置不添加!qb，习惯了也还挺好的。
> > 
> > 
> > 不加!qB在unraid下容易出错，因为unraid文件是分布在不同盘的，如果恰好创建任务的时候所选的盘容量不够，就会导致下载后期出错。只有打开!qB，系统才会分配到容量足够的硬盘。
> 
> 我感觉你说的是预分配下载空间把， !qb就是文件后缀不一样。

对！搞错了

**Comment by xxzj990** [comment]
> > > > 遇到了同样的问题，临时解决方法如下。
> > > > 在需要删除!qB文件的目录执行：
> > > > `find . -name '*.!qB' -exec rm -rf {} \;`
> > > > 一定要在需要删除!qB文件的目录执行，否则有可能把正在下载的文件删掉！
> > > 
> > > 
> > > 这个太暴力了。。 我现在设置不添加!qb，习惯了也还挺好的。
> > 
> > 
> > 不加!qB在unraid下容易出错，因为unraid文件是分布在不同盘的，如果恰好创建任务的时候所选的盘容量不够，就会导致下载后期出错。只有打开!qB，系统才会分配到容量足够的硬盘。
> 
> 我感觉你说的是预分配下载空间把， !qb就是文件后缀不一样。

我一直以为是一个开关，跑过去一看是两个。。。。

**Comment by likun7981** [comment]
贴下配置文件，不要删除`includeExtname`，保留一个空的，像这样`includeExtname:[]`
下个版本我加下判空逻辑

**Comment by likun7981** [comment]
已修复 https://github.com/likun7981/hlink/pull/32
