### ISSUE TITLE
可以在docker容器内使用吗？

### ISSUE THREAD

**Issue by anooki-c** [likun7981/hlink#30]
如题，如果想在docker容器内部使用hlink，要怎么安装呢

**Comment by likun7981** [comment]
> 如题，如果想在docker容器内部使用hlink，要怎么安装呢

暂时没有做docker 镜像，欢迎贡献

**Comment by likun7981** [comment]
> 再请教一下，可以选择不生成文件夹吗

独立文件不生成文件夹？

**Comment by Hiccup90** [comment]
最新的青龙面板支持自动添加依赖
加上hlink之后，即可使用。
