### ISSUE TITLE
使用报错，请作者查看

### ISSUE THREAD

**Issue by aaronkingpz** [likun7981/hlink#31]
Error: Command failed with exit code 1 (EPERM): find /media/4t/qb/hlink -inum 3813379
    at makeError (/usr/local/node/node_global/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/usr/local/node/node_global/lib/node_modules/hlink/node_modules/execa/index.js:187:17)
    at getLinkPath (/usr/local/node/node_global/lib/node_modules/hlink/lib/utils/index.js:72:31)
    at Object.checkLinkExist (/usr/local/node/node_global/lib/node_modules/hlink/lib/utils/index.js:79:17)
    at /usr/local/node/node_global/lib/node_modules/hlink/lib/index.js:115:53
    at step (/usr/local/node/node_global/lib/node_modules/hlink/lib/index.js:33:23)
    at Object.next (/usr/local/node/node_global/lib/node_modules/hlink/lib/index.js:14:53)
    at /usr/local/node/node_global/lib/node_modules/hlink/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/node/node_global/lib/node_modules/hlink/lib/index.js:4:12) {
  command: 'find /media/4t/qb/hlink -inum 3813379',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: 'find: unrecognized: -inum\n' +
    'BusyBox v1.29.2 (2019-03-10 14:44:18 CST) multi-call binary.\n' +
    '\n' +
    'Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]\n' +
    '\n' +
    'Search for files and perform actions on them.\n' +
    'First failed action stops processing of current file.\n' +
    "Defaults: PATH is current directory, action is '-print'\n" +
    '\n' +
    '\t-L,-follow\tFollow symlinks\n' +
    '\t-H\t\t...on command line only\n' +
    "\t-xdev\t\tDon't descend directories on other filesystems\n" +
    '\t-maxdepth N\tDescend at most N levels. -maxdepth 0 applies\n' +
    '\t\t\tactions to command line arguments only\n' +
    "\t-mindepth N\tDon't act on first N levels\n" +
    '\t-depth\t\tAct on directory *after* traversing it\n' +
    '\n' +
    'Actions:\n' +
    '\t( ACTIONS )\tGroup actions for -o / -a\n' +
    "\t! ACT\t\tInvert ACT's success/failure\n" +
    '\tACT1 [-a] ACT2\tIf ACT1 fails, stop, else do ACT2\n' +
    '\tACT1 -o ACT2\tIf ACT1 succeeds, stop, else do ACT2\n' +
    '\t\t\tNote: -a has higher priority than -o\n' +
    '\t-name PATTERN\tMatch file name (w/o directory name) to PATTERN\n' +
    '\t-iname PATTERN\tCase insensitive -name\n' +
    '\t-path PATTERN\tMatch path to PATTERN\n' +
    '\t-ipath PATTERN\tCase insensitive -path\n' +
    '\t-regex PATTERN\tMatch path to regex PATTERN\n' +
    '\t-type X\t\tFile type is X (one of: f,d,l,b,c,s,p)\n' +
    '\t-perm MASK\tAt least one mask bit (+MASK), all bits (-MASK),\n' +
    "\t\t\tor exactly MASK bits are set in file's mode\n" +
    '\t-mtime DAYS\tmtime is greater than (+N), less than (-N),\n' +
    '\t\t\tor exactly N days in the past\n' +
    '\t-mmin MINS\tmtime is greater than (+N), less than (-N),\n' +
    '\t\t\tor exactly N minutes in the past\n' +
    "\t-newer FILE\tmtime is more recent than FILE's\n" +
    '\t-user NAME/ID\tFile is owned by given user\n' +
    '\t-group NAME/ID\tFile is owned by given group\n' +
    '\t-size N[bck]\tFile size is N (c:bytes,k:kbytes,b:512 bytes(def.))\n' +
    '\t\t\t+/-N: file size is bigger/smaller than N\n' +
    "\t-prune\t\tIf current file is directory, don't descend into it\n" +
    'If none of the following actions is specified, -print is assumed\n' +
    '\t-print\t\tPrint file name\n' +
    '\t-print0\t\tPrint file name, NUL terminated\n' +
    '\t-exec CMD ARG ;\tRun CMD with all instances of {} replaced by\n' +
    '\t\t\tfile name. Fails if CMD exits with nonzero\n' +
    '\t-exec CMD ARG + Run CMD with {} replaced by list of file names',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined

Arm v8 node v14.18.1  npm 6.14.15

**Comment by likun7981** [comment]
什么系统，用的什么bash？
