### ISSUE TITLE
THERE ARE SOME ERRORS ON synology 6.23

### ISSUE THREAD

**Issue by sungamma** [likun7981/hlink#37]
RUN THE COMMAND BY ROOT: `hlink "/volume1/movie/TV/" "volume1/movie/TVNEW"`
Error: Command failed with exit code 1 (EPERM): ln /volume1/movie/TV/斛珠夫人.Novoland.Pearl.Eclipse.2021.1080p.WEB-DL.H264.AAC-OurTV/斛珠夫人.Novoland.Pearl.Eclipse.2021.E16.1080p.WEB-DL.H264.AAC-OurTV.mp4 /root/volume1/movie/TVNEW/斛珠夫人.Novoland.Pearl.Eclipse.2021.1080p.WEB-DL.H264.AAC-OurTV
    at makeError (/usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/usr/local/lib/node_modules/hlink/node_modules/execa/index.js:187:17)
    at /usr/local/lib/node_modules/hlink/lib/index.js:141:61
    at step (/usr/local/lib/node_modules/hlink/lib/index.js:52:23)
    at Object.next (/usr/local/lib/node_modules/hlink/lib/index.js:33:53)
    at /usr/local/lib/node_modules/hlink/lib/index.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/hlink/lib/index.js:23:12)
    at /usr/local/lib/node_modules/hlink/lib/index.js:80:65
    at Array.forEach (<anonymous>) {
  command: 'ln /volume1/movie/TV/斛珠夫人.Novoland.Pearl.Eclipse.2021.1080p.WEB-DL.H264.AAC-OurTV/斛珠夫人.Novoland.Pearl.Eclipse.2021.E16.1080p.WEB-DL.H264.AAC-OurTV.mp4 /root/volume1/movie/TVNEW/斛珠夫人.Novoland.Pearl.Eclipse.2021.1080p.WEB-DL.H264.AAC-OurTV',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: 'ln: failed to create hard link ‘/root/volume1/movie/TVNEW/斛珠夫人.Novoland.Pearl.Eclipse.2021.1080p.WEB-DL.H264.AAC-OurTV/斛珠夫人.Novoland.Pearl.Eclipse.2021.E16.1080p.WEB-DL.H264.AAC-OurTV.mp4’ => ‘/volume1/movie/TV/斛珠夫人.Novoland.Pearl.Eclipse.2021.1080p.WEB-DL.H264.AAC-OurTV/斛珠夫人.Novoland.Pearl.Eclipse.2021.E16.1080p.WEB-DL.H264.AAC-OurTV.mp4’: Invalid cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
[HLINK WARN]: 当前文件 斛珠夫人.Novoland.Pearl.Eclipse.2021.E16.1080p.WEB-DL.H264.AAC-OurTV.nfo 不满足配置条件, 跳过创建
[HLINK WARN]: 当前文件 斛珠夫人.Novoland.Pearl.Eclipse.2021.E17.1080p.WEB-DL.H264.AAC-OurTV.mp4.part 不满足配置条件, 跳过创建
[HLINK WARN]: 当前文件 斛珠夫人.Novoland.Pearl.Eclipse.2021.E18.1080p.WEB-DL.H264.AAC-OurTV.mp4.part 不满足配置条件, 跳过创建
[HLINK WARN]: 当前文件 斛珠夫人.Novoland.Pearl.Eclipse.2021.E19.1080p.WEB-DL.H264.AAC-OurTV.mp4.part 不满足配置条件, 跳过创建
[HLINK WARN]: 当前文件 斛珠夫人.Novoland.Pearl.Eclipse.2021.E20.1080p.WEB-DL.H264.AAC-OurTV.mp4.part 不满足配置条件, 跳过创建
[HLINK WARN]: 当前文件 斛珠夫人.Novoland.Pearl.Eclipse.2021.E21.1080p.WEB-DL.H264.AAC-OurTV.mp4.part 不满足配置条件, 跳过创建
[HLINK WARN]: 当前文件 斛珠夫人.Novoland.Pearl.Eclipse.2021.E22.1080p.WEB-DL.H264.AAC-OurTV.mp4.part 不满足配置条件, 跳过创建
[HLINK WARN]: 当前文件 斛珠夫人.Novoland.Pearl.Eclipse.2021.E23.1080p.WEB-DL.H264.AAC-OurTV.mp4.part 不满足配置条件, 跳过创建
[HLINK WARN]: 当前文件 斛珠夫人.Novoland.Pearl.Eclipse.2021.E24.1080p.WEB-DL.H264.AAC-OurTV.mp4.part 不满足配置条件, 跳过创建
[HLINK INFO]: 硬链创建完毕... 总数 427 条
[HLINK INFO]:   成功 0 条
[HLINK INFO]:   失败 113 条
[HLINK INFO]:   跳过 314 条
[HLINK INFO]:   跳过之前的创建记录 0 条, 如果需要重新创建，请在删除或编辑文件 /root/.hlink/cache.json

**Comment by likun7981** [comment]
`Invalid cross-device link` 跨盘

**Comment by sungamma** [comment]
hlink "/volume1/movie/TV/" "volume1/movie/TVNEW" 这哪里跨了盘啊？？ 不都是volume1吗，虽然我有两个盘

**Comment by sungamma** [comment]
看错错误了，缺少了个/
