### ISSUE TITLE
删除硬链接，目录好像有点问题

### ISSUE THREAD

**Issue by slayercjc** [likun7981/hlink#38]
<img width="278" alt="微信截图_20211128110643" src="https://user-images.githubusercontent.com/14236188/143727313-ffde1adf-1d42-4a7a-9108-2e2bab1b14ff.png">

**Comment by slayercjc** [comment]
就是只会删除红色目录，绿色目录还会保留，不知道怎么回事
我用的这个命令，选择的2
`hlink -d "/volume1/PT/电影" "/volume1/Video/电影"`

**Comment by likun7981** [comment]
只会删除一级目录
