### ISSUE TITLE
开个深坑，希望加入删硬链自动同步删源文件功能。

### ISSUE THREAD

**Issue by wgq1991242** [likun7981/hlink#39]
删硬链接目标文件自动同步删源文件。
减少删资源繁琐步骤。
深坑勿扰，哈哈哈。
(*^_^*)

**Comment by likun7981** [comment]
这个占用内存太大了， 需要监控文件变化

**Comment by likun7981** [comment]
折中手段，手动命令行 检测是否源文件被删除，大家可以用定时任务来 定期检测~

**Comment by gfk94508** [comment]
能不能通过命令的方式，用序号列出对应目录所有硬链接路径（mkv的上一级文件夹），通过选择序号（可多选）同时删除硬链接路径和对应源路径文件夹
应用场景：剧集管理软件sonarr对生成的硬链接重命名导入后，因剧集自动更新高质量版本（只会自动删除媒体文件夹低质量版本的硬链接，不会删除种子文件夹低质量版本的源文件），残留了低质量版本的种子通过hlink重新生成硬链接到sonarr文件夹不会自动更名，这个时候只需要在生成的路径列表中找到不符合命名规则的路径删除不会影响媒体库。现在整理是通过手动两边删除，进一步自动化更好。

**Comment by wgq1991242** [comment]
> 折中手段，手动命令行 检测是否源文件被删除，大家可以用定时任务来 定期检测~

能实现就OK的，定时清理这样也不错。最好是双向都能生效。删哪边都不用去找另一边。

**Comment by likun7981** [comment]
https://github.com/likun7981/hlink/releases/tag/v0.6.0-next.1

**Comment by likun7981** [comment]
`npm i -g hlink@next `

**Comment by chenlu964** [comment]
@likun7981 那如何停止监控呢 好像没找到具体的停止监控命令哦

**Comment by likun7981** [comment]
> @likun7981 那如何停止监控呢 好像没找到具体的停止监控命令哦

直接打断进程

**Comment by ayd13swb** [comment]
请问那个42新加的监视模式，是直接复制那个hlink rm -w /path/to/dir就行，还是需要更改路径？然后这个命令的意义就是自动删除已经没有源文件的硬链接，其他的没有影响对吧？谢谢。

**Comment by likun7981** [comment]
> 请问那个42新加的监视模式，是直接复制那个hlink rm -w /path/to/dir就行，还是需要更改路径？然后这个命令的意义就是自动删除已经没有源文件的硬链接，其他的没有影响对吧？谢谢。

这个不完善，更名了检测不到，最好先不要使用

**Comment by likun7981** [comment]
删除命令 建议大家先不要使用，不是很完善，直接手动先删除吧

**Comment by likun7981** [comment]
关闭此issue，使用`hlink prune`，见https://github.com/likun7981/hlink/releases/tag/v0.7.1

删源文件的动作还是太危险
