### ISSUE TITLE
建议加上校验目标目录的文件功能

### ISSUE THREAD

**Issue by MichaelthA** [likun7981/hlink#4]
我用avdc刮削之后目录格式发生变化了，但是文件名字没有变化，简单来说就是一个文件夹变到了另一个文件夹里面，建议加上对目标目录校验，慢点也没啥关系。不然每次都要自己鉴别有点麻烦

**Comment by MichaelthA** [comment]
好吧，文件名变了。希望也加上校验吧👀

**Comment by likun7981** [comment]
已修复，见[CHANGELOG](https://github.com/likun7981/hlink/blob/master/CHANGELOG.md)

**Comment by likun7981** [comment]
请安装hlink@0.2.2
