### ISSUE TITLE
Bug 反馈

### ISSUE THREAD

**Issue by gitnoobbbb** [likun7981/hlink#40]
当视频文件名中含有 空格或 '     
例如:
Guess.Who's.Coming.to.Dinner.1967.720p.BluRay.DD5.1.x264-DON.mkv
Grandma 2015 1080p BluRay DTS x264-VietHD.mkv
程序使用 ls -i 查看硬链接 会提示 no such file or directory导致报错并跳过创建硬链接

**Comment by gitnoobbbb** [comment]
上述报错出现在windows  git bash中
经测试 在linux环境下无此问题

**Comment by wgq1991242** [comment]
用半角引号""标注不行？

**Comment by guoyuejiang** [comment]
> 当视频文件名中含有 空格或 ' 例如: Guess.Who's.Coming.to.Dinner.1967.720p.BluRay.DD5.1.x264-DON.mkv Grandma 2015 1080p BluRay DTS x264-VietHD.mkv 程序使用 ls -i 查看硬链接 会提示 no such file or directory导致报错并跳过创建硬链接

你好，这个问题得到解决了么？
