### ISSUE TITLE
部分电视剧会为每个视频文件新建文件夹

### ISSUE THREAD

**Issue by YangTakeshi** [likun7981/hlink#46]
![1645409533(1)](https://user-images.githubusercontent.com/8491763/154877762-60d7cf23-6e45-4420-ad9c-e5ac149b52ef.png)
之前别的电视剧都没遇到这种情况，今天给隋唐演义创建硬链接的时候老是给每一个文件新建一个文件夹，不知道是什么问题

**Comment by likun7981** [comment]
看下帮助信息，有配置去除的
