### ISSUE TITLE
硬连接是否可以检测源文件的删除？

### ISSUE THREAD

**Issue by HOMMEEN** [likun7981/hlink#49]
打个比方：我源路径下删除了一个文件夹，在执行一次某条命令可以放硬连接的目录也删除这个文件夹？
看完issue #39 感觉没太整明白

**Comment by likun7981** [comment]
删除命令不够完善，后续 会在 #39 持续更新

**Comment by HOMMEEN** [comment]
> 删除命令不够完善，后续 会在 #39 持续更新

好的 感谢回复
