### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by dizicheng** [likun7981/hlink#52]
win10
映射的网络驱动器
git bash
报错信息如下：
 Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
node.js版本：12.20
#43

**Comment by dizicheng** [comment]
![image](https://user-images.githubusercontent.com/21209008/169015875-a03d137d-4752-4bc5-976d-cd03a7240ba4.png)

**Comment by dizicheng** [comment]
[配置 .txt](https://github.com/likun7981/hlink/files/8715347/default.txt)

**Comment by likun7981** [comment]
请更新下你的node版本，node版本不对

**Comment by likun7981** [comment]
ok，我会在这周末尽量解决这个问题

**Comment by likun7981** [comment]
问题排查中，时间会稍微晚点

**Comment by likun7981** [comment]
我在windows上面并没有复现你提到的问题，我看了你的配置文件，我觉得应该是你配置的source和dest路径有问题，
你可以在你的目录下面使用pwd来得到绝对路径，像下面这样
![image](https://user-images.githubusercontent.com/13427467/169839594-4ab47263-0b9e-4873-b592-e231f9572683.png)

这个issue我就先关掉了，如果你还不能成功，可以继续在下面留言

**Comment by dizicheng** [comment]
![image](https://user-images.githubusercontent.com/21209008/169843892-9d271212-a428-4427-95b3-bc582980be8a.png)
重复一遍，我是通过nas的Samba功能映射的文件夹，参见 #43 老版本一样的路径可以成功。

**Comment by dizicheng** [comment]
test
 ├── a
 │   └── a.mp4
 └── b
![image](https://user-images.githubusercontent.com/21209008/169847031-d572ab7a-c59d-4b15-b2e5-523d110ab0af.png)

**Comment by likun7981** [comment]
对 这就是 Progress bar 导致的问题，实际是成功了的，你可以更新到 0.7.4。就不会再有这个问题了

**Comment by likun7981** [comment]
https://github.com/likun7981/hlink/releases/tag/v0.7.4，你可以看下这个tag的发布说明

**Comment by likun7981** [comment]
我先打开这个issue，用于追踪在windows上使用配置文件的问题，后续修复后，我再来关闭它
