### ISSUE TITLE
希望能增加选项排除特定名称文件夹。（比如群晖全局搜索到处产生的@eaDir文件夹）

### ISSUE THREAD

**Issue by Imoagn** [likun7981/hlink#54]
希望能排除特定文件夹，现在因为@eaDir这种隐藏文件夹会产生写入冲突，即各种“目标地址文件已经存在“。 也不知道成功的@eaDir中的硬链是否影响了@eaDir的运作。 

多谢

**Comment by likun7981** [comment]
好了 后续考虑下

**Comment by jawn-ha** [comment]
首先感谢作者的工具！
这边同样的需求，求增加

**Comment by likun7981** [comment]
我先关闭这个issue，后续在 https://github.com/likun7981/hlink/issues/12 进行追踪，都是同样的述求
