### ISSUE TITLE
建议用base和target取代reverse

### ISSUE THREAD

**Issue by sjtuross** [likun7981/hlink#63]
hlink prune 基准路径 目标路径

如果把路径定义成基准和目标，感觉就不需要reverse了，而且便于理解

所有硬链接的文件都是指向同一块数据，不用去想谁是源文件，谁是硬链接

**Comment by likun7981** [comment]
之前这样考虑过，但是如果用基准路劲 和 目标路劲，会有一个问题，有硬链缓存这个东西，所以reverse除了标识 源目录和硬链目录，还关系着是否需要处理 硬链缓存

**Comment by likun7981** [comment]
因为硬链目录的基准并不是和源目录一一对应的

相当于是 `源目录 - 缓存文件 = 硬链目录`，所以 用 源目录为基准目录的时候（正向）则不需要过滤缓存文件，但是用 硬链目录作为基准目录的时候，是需要过滤缓存文件的

**Comment by likun7981** [comment]
后面考虑 使用配置文件来直接渠道命令行 录入配置。这样就不用考虑对应关系了，像下面这样~

```javascript
// hlink.config.mjs
export default {
	paths: {
		sourcePath1: destPath1,
		sourcePath2: destPath2,
	},
	// 其他配置
}
```
