### ISSUE TITLE
以Docker方式使用hlink

### ISSUE THREAD

**Issue by sjtuross** [likun7981/hlink#64]
UNRAID环境中使用，写了个简单的Dockerfile

```Dockerfile
FROM node:16-alpine
RUN npm i -g hlink
ENTRYPOINT [ "hlink" ]
```

构建镜像后，运行下面的命令就可以创建硬链接了，仅供参考

`docker run --rm -v /mnt:/mnt sjtuross/hlink /mnt/user/media/source /mnt/user/media/dest`

**Comment by likun7981** [comment]
欢迎提mr 完善下 使用文档

**Comment by likun7981** [comment]
https://github.com/likun7981/hlink/releases/tag/v2.0.0-next.13
