### ISSUE TITLE
求助：如何删除openCache打开后产生的缓存

### ISSUE THREAD

**Issue by mirrorhui520** [likun7981/hlink#67]
如题，之前由于理解错误，把配置文件中的opernCache打开了，后面移走或删除了硬链没有再次生成了，请问一下如何解决？

**Comment by likun7981** [comment]
`rm ~/.hlink/cache-array.json` 按道理是有提示的~~

**Comment by mirrorhui520** [comment]
> `rm ~/.hlink/cache-array.json`按道理是有提示的~~

谢谢
