### ISSUE TITLE
使用出错

### ISSUE THREAD

**Issue by claresongs** [likun7981/hlink#83]
平台为群晖ds920+

![image](https://user-images.githubusercontent.com/44543227/181482053-3ee4c253-9fef-4a4a-9c40-dfdf8d7f0d74.png)

**Comment by claresongs** [comment]
node.js 16.13.1-1006

**Comment by MichaelthA** [comment]
同样遇到这个问题，DS3617

**Comment by likun7981** [comment]
看下2.0的文档，已经不支持命令行录入了源目录和目标目录了，只能用配置文件

**Comment by likun7981** [comment]
推荐使用webui，`hlink start`即可启动webui

**Comment by MichaelthA** [comment]
> 推荐使用webui，`hlink start`即可启动webui

2.0遇到不支持bash输入，然后报错

**Comment by claresongs** [comment]
> 推荐使用webui，`hlink start`即可启动webui



> > 推荐使用webui，`hlink start`即可启动webui
> 
> 2.0遇到不支持bash输入，然后报错

确实,webui已经正常使用了,感谢二位
