### ISSUE TITLE
问两个小问题：定时任务扫描是全盘扫描还是增量扫描？

### ISSUE THREAD

**Issue by huiyanga** [likun7981/hlink#88]
问两个小问题：
我是docker安装的
设置了定时任务，想问一下在硬链接成功后的定时扫描，是全盘批量扫描还是增量扫描？
第二个问题，就是脚本是下载完成后执行，对我这种新手不是很懂。（就是想要一个说明教程，比如是在哪设置计划任务，下载器下载完成了，脚本执行。）

**Comment by likun7981** [comment]
图形界面上应该一目了然了吧~按照界面上一步一步走就可以了
