### ISSUE TITLE
希望加入后缀名过滤黑名单功能

### ISSUE THREAD

**Issue by wgq1991242** [likun7981/hlink#9]
目前程序支持的后缀名过滤白名单功能满足99%需求。

但是某些特殊资源后缀名不常见，如果没有写在规则里，很可能链接不到。
比如很多原盘、图书，含有很多奇奇怪怪的类型文件。

如果能加入黑名单功能，我们就可以只排除.nfo、.jpg、.png等影响刮削的文件类型，而对其他所有文件都进行链接。
满足不同需求，更加完美。

**Comment by likun7981** [comment]
已发布 beta版本 有黑名单功能，使用`npm i -g hlink@beta` 进行安装体验，有问题环境及时反馈
https://github.com/likun7981/hlink/releases/tag/v0.3.0-0
