### ISSUE TITLE
硬链接创建的文件夹的所有者为root，权限问题，无法重命名文件。

### ISSUE THREAD

**Issue by isunbnn** [likun7981/hlink#90]
大佬你好，我是unraid下docker使用，硬链接了一个文件夹下文件到另外一个**文件夹**（此文件夹非自行新建，由hlink配置文件新建）。
现在出现了一个问题hlink创建的文件夹的**所有者**为**root**，文件 **所有者**为创建的**user**用户，然后权限是：所有者:**读/写**Group:**只读** Other:**只读**。
 这样就遇到局域网smb共享无法重命名文件，只有把**所有者**改为**user**，权限里面Group改成**读/写**，这样才能正常在windows下重命名。请问有办法解决吗？

**Comment by likun7981** [comment]
docker创建的时候指定下用户身份是否可行？

**Comment by isunbnn** [comment]
> docker创建的时候指定下用户身份是否可行？

docker设置了PUIDPGID，填什么都是没有变化的，文件夹所有者和权限也没有变化。

**Comment by QingLiang2021** [comment]
同样的问题，设置了puid和guid，创建的硬链接的所有者还是root。

**Comment by YuLianChen** [comment]
同样的问题，也是这个问题让我不得不放弃手动刮削，转向全自动

**Comment by ReddotCleaner** [comment]
同样是unraid存在同样问题

**Comment by likun7981** [comment]
OK，我后面空了看下这个问题

**Comment by FormatToday** [comment]
同样的问题，设置过PUID、PGID、UMASK都没有用。
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/20515769/192243787-1f97b684-0478-4fa8-97f6-58c1a0c42000.png">

**Comment by wc906398139** [comment]
同样的问题，权限指定，一直都是root用户下，无法修改文件 头痛。

**Comment by Stonestonestone** [comment]
同上，权限太高，其他用户没有办法修改名字

**Comment by DDS-ALL** [comment]
作者可以看一下我做的镜像
https://github.com/DDS-Derek/Hlink-Docker
对于解决这个问题肯定有帮助的

**Comment by DDS-ALL** [comment]
其实PUID和PGID本身就不是docker自带的，都是镜像作者自己编写和适配的，我认为作者对于docker也不是很了解，所以可以看一下我制作的镜像，或者直接使用我制作的镜像

**Comment by likun7981** [comment]
> 其实PUID和PGID本身就不是docker自带的，都是镜像作者自己编写和适配的，我认为作者对于docker也不是很了解，所以可以看一下我制作的镜像，或者直接使用我制作的镜像

确实 了解不够深入，欢迎提mr，大家都一起使用一个 docker

**Comment by DDS-ALL** [comment]
> > 其实PUID和PGID本身就不是docker自带的，都是镜像作者自己编写和适配的，我认为作者对于docker也不是很了解，所以可以看一下我制作的镜像，或者直接使用我制作的镜像
> 
> @DDS-ALL 确实 了解不够深入，欢迎提mr，大家都一起使用一个 docker

那我这边准备一下，过一会提交一个PR

**Comment by DDS-ALL** [comment]
> > 其实PUID和PGID本身就不是docker自带的，都是镜像作者自己编写和适配的，我认为作者对于docker也不是很了解，所以可以看一下我制作的镜像，或者直接使用我制作的镜像
> 
> @DDS-ALL 确实 了解不够深入，欢迎提mr，大家都一起使用一个 docker

https://github.com/likun7981/hlink/pull/112

**Comment by likun7981** [comment]
#112 MR 已完成，再次感谢 @DDS-ALL
