### ISSUE TITLE
希望加入日志功能

### ISSUE THREAD

**Issue by jinaoao** [likun7981/hlink#91]
希望可以加入日志功能，定时任务执行目前无法查看日志，加入日志功能可以查看定时任务的结果

**Comment by likun7981** [comment]
什么形式？命令行还是docker？

**Comment by jinaoao** [comment]
> 什么形式？命令行还是docker？

docker

**Comment by likun7981** [comment]
在docker控制台应该有对应的日志

**Comment by likun7981** [comment]
我先关掉这个issue，如果有需要的，可以再次打开回复
