### ISSUE TITLE
最新的版本,源目录不固定的情况如何使用hlink生成硬链,每次都要改配置吗

### ISSUE THREAD

**Issue by HappyQuQu** [likun7981/hlink#93]
最新的版本,源目录不固定的情况如何使用hlink生成硬链,每次都要改配置吗
以前老版本 命令行可以 每次指定源目录,现在新的版本webui上好像不支持了

**Comment by likun7981** [comment]
生成多个配置文件。每次指定不同的配置文件。webui 支持创建多个配置文件，也支持一个配置文件配置多个不同的源目录

**Comment by likun7981** [comment]
看下文档 https://hlink.likun.me/other/v2.html
