### ISSUE TITLE
链接失败

### ISSUE THREAD

**Issue by penwyp** [likun7981/hlink#94]
错误堆栈：
/volume2/pt/电影/香港/古惑仔六部高清全集 [国粤双语简繁字幕]/古惑仔6之胜者为王BD/@eaDir/Young.and.Dangerous.VI.2000.BluRay.1080p.H265.10bit.AC3.2Audio.mkv:
206635551 SYNOINDEX_MEDIA_INFO*
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async lsirf (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/lsirfl.js:8:22)
    at async getInodes (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/parseLsirfl.js:44:6)
    at async Promise.all (index 0)
    at async getRmFiles (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/prune/getRmFiles.js:14:30)
    at async prune (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/prune/index.js:34:29)

文件目录信息：
# ll "/volume2/pt/电影/香港/古惑仔六部高清全集 [国粤双语简繁字幕]/古惑仔6之胜者为王BD"                                                                                                                              [0:40:49]
total 7.3G
----------+ 1 root root 444K Sep  3 12:05  COVER.jpg
drwxrwxrwx+ 3 root root 4.0K Sep 21 00:25  @eaDir
----------+ 1 root root 7.3G Sep  3 12:09  Young.and.Dangerous.VI.2000.BluRay.1080p.H265.10bit.AC3.2Audio.mkv
----------+ 1 root root 238K Sep  3 12:09 '古惑仔6之胜者为王 (2000) A.jpg'
----------+ 1 root root 287K Sep  3 12:09 '古惑仔6之胜者为王 (2000) B.jpg'

运行环境：
群晖DSM7.0

# node --version                                                                                                                                                                                                   
v16.13.1

# npm --version    
8.1.2

# hlink --version       
2.0.6

**Comment by penwyp** [comment]
docker版本也遇到同样问题

**Comment by likun7981** [comment]
> 错误堆栈： /volume2/pt/电影/香港/古惑仔六部高清全集 [国粤双语简繁字幕]/古惑仔6之胜者为王BD/@eaDir/Young.and.Dangerous.VI.2000.BluRay.1080p.H265.10bit.AC3.2Audio.mkv: 206635551 SYNOINDEX_MEDIA_INFO* at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11) at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async lsirf (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/lsirfl.js:8:22) at async getInodes (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/parseLsirfl.js:44:6) at async Promise.all (index 0) at async getRmFiles (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/prune/getRmFiles.js:14:30) at async prune (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/prune/index.js:34:29)
> 
> 文件目录信息：
> 
> # ll "/volume2/pt/电影/香港/古惑仔六部高清全集 [国粤双语简繁字幕]/古惑仔6之胜者为王BD" [0:40:49]
> total 7.3G ----------+ 1 root root 444K Sep 3 12:05 COVER.jpg drwxrwxrwx+ 3 root root 4.0K Sep 21 00:25 @eadir ----------+ 1 root root 7.3G Sep 3 12:09 Young.and.Dangerous.VI.2000.BluRay.1080p.H265.10bit.AC3.2Audio.mkv ----------+ 1 root root 238K Sep 3 12:09 '古惑仔6之胜者为王 (2000) A.jpg' ----------+ 1 root root 287K Sep 3 12:09 '古惑仔6之胜者为王 (2000) B.jpg'
> 
> 运行环境： 群晖DSM7.0
> 
> # node --version
> v16.13.1
> 
> # npm --version
> 8.1.2
> 
> # hlink --version
> 2.0.6

提供下截图

**Comment by likun7981** [comment]
> 一样的问题。 file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59 error = new Error(message); ^
> 
> Error: Command failed with exit code 1: ls -iRFL /PT/QB ls: /PT/QB/logs: No such file or directory /PT/QB: at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11) at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async lsirf (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/lsirfl.js:8:22) at async getInodes (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/parseLsirfl.js:44:6) at async analyse (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/analyse.js:15:23) at async Promise.all (index 0) at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:27:6) at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) { shortMessage: 'Command failed with exit code 1: ls -iRFL /PT/QB', command: 'ls -iRFL /PT/QB', escapedCommand: 'ls -iRFL "/PT/QB"', exitCode: 1, signal: undefined, signalDescription: undefined, stdout: '/PT/QB:', stderr: 'ls: /PT/QB/logs: No such file or directory', failed: true, timedOut: false, isCanceled: false, killed: false }

你这个是文件不存在的原因
