### ISSUE TITLE
群晖无法开机启动

### ISSUE THREAD

**Issue by yjiawqgj** [likun7981/hlink#96]
断了一次电，重启后，输入群晖IP加9090打不开呀。

**Comment by likun7981** [comment]
用的什么方式？docker？命令行？

**Comment by yjiawqgj** [comment]
> 用的什么方式？docker？命令行？

群晖920+,对,使用的命令行，hlink start，并没有启动。而且你那个自动 脚本放在transsmision里不管用呀怎么用你这个脚本自动触发任务？

**Comment by likun7981** [comment]
transmissin 的执行任务建议你看下文档，必须使用sh的文件。自启动底层采用的 https://github.com/typicode/user-startup  非自己实现，或许你可以去这里提个issue。如果确实无法解决，建议你使用docker

**Comment by yjiawqgj** [comment]
tr问题早已解决，等你这回复黄花菜都凉了。
